In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [6]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [7]:
data.head(5)

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [8]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [20]:
#Creating the Multiple regression
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

## Standardization

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [25]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [27]:
x_scaled = scaler.transform(x)

## Regression With scaled Features

In [29]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
reg.intercept_

3.330238095238095

In [31]:
reg.coef_

array([ 0.17181389, -0.00703007])

## Summary

In [33]:
reg_summary = pd.DataFrame(['Bias', 'SAT', 'Rand 1,2,3'],  columns = ['Features'])

In [34]:
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [35]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making Predictions With the Cefficients(Weights)

In [36]:
new_data = pd.DataFrame(data = [[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])

In [37]:
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [44]:
new_data_scaled = scaler.transform(new_data)

In [45]:
new_data_scaled

array([[-1.,  1.],
       [ 1., -1.]])

In [47]:
reg.predict(new_data_scaled)

array([3.15139414, 3.50908205])

In [69]:
new_data_2_scaled = x_scaled[:,0].reshape(-1,1)

In [70]:
new_data_2_scaled

array([[-1.26338288],
       [-1.74458431],
       [-0.82067757],
       [-1.54247971],
       [-1.46548748],
       [-1.68684014],
       [-0.78218146],
       [-0.78218146],
       [-0.51270866],
       [ 0.04548499],
       [-1.06127829],
       [-0.67631715],
       [-1.06127829],
       [-1.28263094],
       [-0.6955652 ],
       [ 0.25721362],
       [-0.86879772],
       [-1.64834403],
       [-0.03150724],
       [-0.57045283],
       [-0.81105355],
       [-1.18639066],
       [-1.75420834],
       [-1.52323165],
       [ 1.23886453],
       [-0.18549169],
       [-0.5608288 ],
       [-0.23361183],
       [ 1.68156984],
       [-0.4934606 ],
       [-0.73406132],
       [ 0.85390339],
       [-0.67631715],
       [ 0.09360513],
       [ 0.33420585],
       [ 0.03586096],
       [-0.35872421],
       [ 1.04638396],
       [-0.65706909],
       [-0.13737155],
       [ 0.18984542],
       [ 0.04548499],
       [ 1.1618723 ],
       [-1.37887123],
       [ 1.39284898],
       [ 0

In [71]:
reg_simple = LinearRegression()

In [75]:
reg_simple.fit(new_data_2_scaled, y)
reg_simple.predict(new_data_2_scaled[:,0].reshape(-1,1))

array([3.11288962, 3.03010522, 3.18905127, 3.06487466, 3.07812017,
       3.04003934, 3.19567402, 3.19567402, 3.24203329, 3.33806319,
       3.14765907, 3.21388659, 3.14765907, 3.10957824, 3.21057521,
       3.37448833, 3.18077283, 3.0466621 , 3.32481769, 3.23209916,
       3.19070696, 3.12613512, 3.02844953, 3.06818604, 3.54336851,
       3.29832668, 3.23375485, 3.29004824, 3.61953016, 3.24534466,
       3.20395246, 3.47714099, 3.21388659, 3.34634163, 3.38773383,
       3.3364075 , 3.26852429, 3.51025475, 3.21719796, 3.30660512,
       3.36289851, 3.33806319, 3.53012301, 3.09302136, 3.56985952,
       3.4622398 , 3.2950153 , 3.51356613, 3.34965301, 3.55164695,
       3.25859017, 3.34634163, 3.43243741, 2.98043457, 3.38607815,
       3.39932365, 3.13938063, 3.50859906, 3.22382072, 3.4059464 ,
       3.52681163, 3.26852429, 3.40925778, 3.65429961, 3.40925778,
       3.30826081, 3.33806319, 3.47714099, 3.35627576, 3.47217392,
       3.4754853 , 3.21885365, 3.5450242 , 3.47714099, 3.62118