In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [5]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## Creating Targets

In [7]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [9]:
data_preprocessed['Excessive Absenteeism'] = targets

In [10]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [13]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [14]:
data_with_targets is data_preprocessed

False

In [15]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0                 30          0         2    1                      1  
1                 31          0         1    0                      0  
2                 31          0         0    0                      0  
3                 24          0         2    0                      1  
4                 30          0         2    1                      0  
..               ...        ...       ...  ...                    ...  
695               22          1         2    0                      1  
696               24          0         1    2                      0  
697               25          1         0    0                      1  
698               25          1         0    0                      0  
699               25          0         1    1                      0  

[700 rows x 15 columns]

## Selecting Inputs

In [19]:
unscaled_inputs = data_with_targets.iloc[:, 0:14]

## Standardizing

In [20]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [25]:
scaled_inputs.shape

(700, 14)

## Train Test Split and Shuffle then Data

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.01928035,  2.8430157 ],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,train_size = 0.8, random_state = 365)

## Model

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the Model

In [31]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
reg.score(x_train, y_train)

0.775

## Maually Checking the Accuracy

In [33]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [35]:
np.sum((model_outputs == y_train))

434

In [36]:
model_outputs.shape[0]

560

In [37]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.775

## Finding Intercept and Coefficients

In [38]:
reg.intercept_

array([-0.11211731])

In [39]:
reg.coef_

array([[ 2.00957995,  0.65943731,  1.49181047,  1.32704747,  0.09866367,
        -0.11383455,  0.62652881, -0.10098136, -0.30486508, -0.03947569,
         0.39632678, -0.09500841,  0.44226972, -0.37530396]])

In [40]:
feature_names = unscaled_inputs.columns.values

In [41]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Reason_1     2.009580
1                  Reason_2     0.659437
2                  Reason_3     1.491810
3                  Reason_4     1.327047
4               Month Value     0.098664
5           Day of the Week    -0.113835
6    Transportation Expense     0.626529
7          Distance to Work    -0.100981
8                       Age    -0.304865
9   Daily Work Load Average    -0.039476
10          Body Mass Index     0.396327
11                Education    -0.095008
12                 Children     0.442270
13                      Pet    -0.375304

In [43]:
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.112117
1                  Reason_1     2.009580
2                  Reason_2     0.659437
3                  Reason_3     1.491810
4                  Reason_4     1.327047
5               Month Value     0.098664
6           Day of the Week    -0.113835
7    Transportation Expense     0.626529
8          Distance to Work    -0.100981
9                       Age    -0.304865
10  Daily Work Load Average    -0.039476
11          Body Mass Index     0.396327
12                Education    -0.095008
13                 Children     0.442270
14                      Pet    -0.375304

In [45]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [47]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.112117    0.893939
1                  Reason_1     2.009580    7.460183
2                  Reason_2     0.659437    1.933704
3                  Reason_3     1.491810    4.445136
4                  Reason_4     1.327047    3.769896
5               Month Value     0.098664    1.103695
6           Day of the Week    -0.113835    0.892406
7    Transportation Expense     0.626529    1.871104
8          Distance to Work    -0.100981    0.903950
9                       Age    -0.304865    0.737223
10  Daily Work Load Average    -0.039476    0.961293
11          Body Mass Index     0.396327    1.486355
12                Education    -0.095008    0.909365
13                 Children     0.442270    1.556235
14                      Pet    -0.375304    0.687080

## Testing

In [49]:
reg.score(x_test, y_test)

0.75

In [50]:
predicted_proba = reg.predict_proba(x_test)

In [51]:
predicted_proba

array([[0.5130517 , 0.4869483 ],
       [0.58990371, 0.41009629],
       [0.33358782, 0.66641218],
       [0.1022197 , 0.8977803 ],
       [0.22039578, 0.77960422],
       [0.31161216, 0.68838784],
       [0.18689792, 0.81310208],
       [0.8638876 , 0.1361124 ],
       [0.55641851, 0.44358149],
       [0.31495472, 0.68504528],
       [0.87121969, 0.12878031],
       [0.88803904, 0.11196096],
       [0.67347306, 0.32652694],
       [0.38140679, 0.61859321],
       [0.28563868, 0.71436132],
       [0.92985859, 0.07014141],
       [0.49360503, 0.50639497],
       [0.56794569, 0.43205431],
       [0.74766416, 0.25233584],
       [0.78841704, 0.21158296],
       [0.98375213, 0.01624787],
       [0.69841524, 0.30158476],
       [0.35071626, 0.64928374],
       [0.53226302, 0.46773698],
       [0.87024969, 0.12975031],
       [0.44197403, 0.55802597],
       [0.80850126, 0.19149874],
       [0.96160932, 0.03839068],
       [0.31124378, 0.68875622],
       [0.68044994, 0.31955006],
       [0.

## Saving the Model

In [52]:
import pickle

In [53]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [54]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)